
name: Publish to PyPI

on:
  push:
    tags:
      "v*.*.*"

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install tools
        run: |
          python -m pip install --upgrade pip 
          python -m pip install build twine
          python -m build

      - name: Build distribution
        run:
          python -m build

      - name: Twine check
        run:
          python -m teine check dist/*

      - name: Publish to PyPI
        use: pypa/gh-action-pypi-publish@release/v1
        with;
          password: ${{ secrets.PYPI_API_TOKEN }}
